---
title: "Raw Datasets Used for Analysis"
---
### Drug Price

  + Found [here](https://data.medicaid.gov/resource/tau9-gfwr.cs)
* It contains weekly drug prices from November 2013 to October 2017 recorded. 

### NIH Funding

* The NIH RCDC Report
* This dataset contains the annual support for various disease categories based on grants, contracts, and other funding mechanisms used across the National Institutes of Health (NIH).  Prevalence and mortality data included in this dataset is from the National Center for Health Statistics (NCHS) at the Centers for Disease Control & Prevention (CDC).
  + Explore [here](https://report.nih.gov/categorical_spending.aspx)
  
### Patents
* The Patents [dataset](https://www.fda.gov/Drugs/InformationOnDrugs/ucm129689.htm) from the FDA Orange Book

### Products
* The Products [dataset](https://www.fda.gov/Drugs/InformationOnDrugs/ucm129689.htm) from the FDA Orange Book

### Exclusivity

### Ingredient

### Drugs By Condition
* Scraping data on drugs per condition from [this website](https://www.centerwatch.com/drug-information/fda-approved-drugs/medical-conditions/A)

### Chronic Diseases
* Scrapping data on chronic diseases from three websites. 
  + [First](https://www.medicalschemes.com/medical_schemes_pmb/chronic_disease_list.htm)
  + [Second](http://www.health24.com/Medical-schemes/PMB-and-chronic-disease/List-of-chronic-diseases-20120721)
  + [Third](https://www.cms.gov/Research-Statistics-Data-and-Systems/Statistics-Trends-and-Reports/Chronic-Conditions/CC_Main.html)
  
  
  Additional References
  
    + https://www.drugabuse.gov/drugs-abuse/prescription-drugs-cold-medicines
    
    + https://www.marylandaddictionrecovery.com/top-10-most-abused-prescription-drugs
    
    + https://newlifehouse.com/top-10-commonly-abused-prescription-medications/
    
    + https://www.cbsnews.com/news/mixing-opioids-oxycodone-and-popular-sedatives-xanax-may-be-deadly/
    + https://www.washingtonpost.com/lifestyle/style/soft-smooth-and-steady-how-xanax-turned-american-music-into-pill-pop/2017/04/19/535a44de-1955-11e7-bcc2-7d1a0973e7b2_story.html?utm_term
    + https://www.washingtonpost.com/lifestyle/style/soft-smooth-and-steady-how-xanax-turned-american-music-into-pill-pop/2017/04/19/535a44de-1955-11e7-bcc2-7d1a0973e7b2_story.html
    
  + https://www.forbes.com/2010/05/11/narcotic-painkiller-vicodin-business-healthcare-popular-drugs.html#212b328b787f
