---
title: "Data Wrangling"
---
We used the following [variables](variables.html) in our analysis.

We accessed many [raw datasets](data.html) to complete project.

* The code chunks below were used for loading and tidying the data.

  + We put all sub-datasets in long format. We renamed variables as necessary. 
 
  + We restricted our final dataset to contain only non-solution drugs. These drugs are described as “each” or “per gram.” We omitted all solution-type drugs because the Drug Price dataset did not specify if liquid drugs were drinkable solutions or injectable.  Also all drugs were measured by two different units: mills and grams. Therefore, we could not adequately compare between solution and per gram/each type of drugs. 
 
  + The Drug Price Excel dataset had over 5 million observations. To representatively condense this dataset, we averaged monthly drug price for each drug into a yearly “avg_price” variable.  Essentially, each unique drug observation had 12 drug prices for each month of a year. We averaged these 12 drug prices into one average price for the year. This condensed the Drug Price dataset to approximately 2.5 million observations. 
 
  + We joined patents, products, exclusivity, ingredient, drug_disease_data, final_nih_funding, and drug_price and chronic_diseases_final into our Final Dataset named final_dataset. We used the variables ingredient, application_no, product_no, drug_type, trade_name, otc, and disease as keys for joining (inner and left).