---
title: "Variables"
---
The variables that we retained are: 

* trade_name: the trade name of the drug

* drug_type: the drug type (B: Brand or G: Generic)

* otc: over the counter drug (Yes or No)

* pricing_unit: EA for each, GM for gram, and ML for milliliters

* year: the funding and pricing year

* avg_price: the average price for the particular year

* dose_form: the dose form (tablet, solution, solution injectable)

* route: route of administration (oral or IV)

* strength: the strength of the dose

* application_no: the FDA assigned number to the drug application.

* product_no: The FDA assigned number to identify the application products; used for joining datasets.

* approval_year: the year the patent was approved

* app_full: the full name of the company that developed the drug

* active_ingredient: the active ingredient

* ingredient: the active ingredients in a wide format; used for joining datasets

* patent_num: the patent number

* pediatric_exclusivity_granted: yes or no

* year_pat_expires: the patent expiration year

* year_excl_expires: the exclusivity expiration year

* disease: the disease the drug treats

* prevalence: the disease prevalence for 2015

* US_mortality_2015: the disease mortality rate

* funding: the NIH funding for disease research in millions

* disease_type: the type disease (acute or chronic)